[project]
name = "zartist"
version = "0.1.0"
dependencies = [
    "fastmcp>=2.1.2",
    "mcp[cli]>=1.6.0",
    "regex>=2024.11.6",
    "requests>=2.32.3",
    "pillow>=10.0.0",
    "pandas>=2.2.3",
    "openai>=1.74.0",
]
